uploads = []
generated = []

[[outputs]]
id = "DSxWsKnazfiLOsE0vjjFU"
uri = "file://.local/crown-infrastructure-audit.md"
type = "text"
title = "Crown Program Infrastructure Audit"

[[outputs]]
id = "xFO1o_z5jE1geigtRHOAi"
uri = "file://charlotte_hubs_and_zips.csv"
type = "table"
title = "Charlotte Hubs & ZIP Codes"
