import { openMetro } from "../metro/launchWorkflow";
import { createComingSoonPage } from "../metro/comingSoon";
import { createMetroFromTemplate, getMetroChecklist, updateChecklistItem, updateMetroStatus } from "../metro/metroCloneService";
import { getPlatformPrice, getEffectivePrice, getEffectivePriceByKey } from "../stripe/platformPricing";
import { auditStripeSync, getPricingSummary } from "../stripe/stripeSyncService";
import { handleCoraRequest } from "./service";
import { suggestSources, generateFromApprovedSources } from "./contentBridge";
import { selectContentSources } from "./sourceSelector";
import { resolveHat } from "./hats";
import { createPlan, approvePlan, rejectPlan, getPlan, listPlans } from "./planService";
import { buildFromPlan, listBuildLogs, getBuildLog } from "./buildService";
import { revertBuild } from "./revertService";
import { createOutreachDraft, approveOutreach, archiveOutreach, updateOutreach, getOutreach, listOutreach, createVoiceScriptDraft } from "./outreachService";
import { createUiProposal, approveProposal, revertProposal, updateProposal, getProposal, listProposals } from "./uiProposalService";
import { isRecommendationRequest, formatRecommendationResponse } from "./responseDoctrine";
import { createVoiceProfile, getVoiceProfile, listVoiceProfiles, updateVoiceProfile, activateVoiceProfile, archiveVoiceProfile, seedDefaultVoiceProfiles } from "./ai_voice_service";
import { createCallCampaign, getCallCampaign, listCallCampaigns, updateCallCampaign, transitionCampaignStatus, archiveCallCampaign, createCallTask, listCallTasks, updateCallTask } from "./ai_call_campaign_service";
import { createAnswerFlow, getAnswerFlow, listAnswerFlows, updateAnswerFlow, approveAnswerFlow, rejectAnswerFlow, archiveAnswerFlow } from "./ai_answer_flow_service";
import { createOutboundFlow, getOutboundFlow, listOutboundFlows, updateOutboundFlow, approveOutboundFlow, rejectOutboundFlow, archiveOutboundFlow } from "./ai_outbound_flow_service";
import { getVoiceProvider, isVoiceProviderConfigured } from "./ai_voice_provider";
import { generateSnapshot, getSnapshot, listSnapshots } from "./operatorSnapshotService";
import { createOpportunity, getOpportunity, listOpportunities, updateOpportunity, approveOpportunity, archiveOpportunity } from "./opportunityService";
import { createBlocker, getBlocker, listBlockers, updateBlocker, resolveBlocker, ignoreBlocker } from "./blockerService";
import { createNextAction, getNextAction, listNextActions, updateNextAction, completeNextAction, skipNextAction } from "./nextActionService";
import { getMetroReadiness, getAllMetroReadiness } from "./metroReadinessService";

export const coraTools = {
  openMetro,
  createComingSoonPage,
  createMetroFromTemplate,
  getMetroChecklist,
  updateChecklistItem,
  updateMetroStatus,
  getPlatformPrice,
  getEffectivePrice,
  getEffectivePriceByKey,
  auditStripeSync,
  getPricingSummary,
  handleCoraRequest,
  suggestSources,
  generateFromApprovedSources,
  selectContentSources,
  resolveHat,
  createPlan,
  approvePlan,
  rejectPlan,
  getPlan,
  listPlans,
  buildFromPlan,
  listBuildLogs,
  getBuildLog,
  revertBuild,
  createOutreachDraft,
  approveOutreach,
  archiveOutreach,
  updateOutreach,
  getOutreach,
  listOutreach,
  createVoiceScriptDraft,
  createUiProposal,
  approveProposal,
  revertProposal,
  updateProposal,
  getProposal,
  listProposals,
  isRecommendationRequest,
  formatRecommendationResponse,
  createVoiceProfile,
  getVoiceProfile,
  listVoiceProfiles,
  updateVoiceProfile,
  activateVoiceProfile,
  archiveVoiceProfile,
  seedDefaultVoiceProfiles,
  createCallCampaign,
  getCallCampaign,
  listCallCampaigns,
  updateCallCampaign,
  transitionCampaignStatus,
  archiveCallCampaign,
  createCallTask,
  listCallTasks,
  updateCallTask,
  createAnswerFlow,
  getAnswerFlow,
  listAnswerFlows,
  updateAnswerFlow,
  approveAnswerFlow,
  rejectAnswerFlow,
  archiveAnswerFlow,
  createOutboundFlow,
  getOutboundFlow,
  listOutboundFlows,
  updateOutboundFlow,
  approveOutboundFlow,
  rejectOutboundFlow,
  archiveOutboundFlow,
  getVoiceProvider,
  isVoiceProviderConfigured,
  generateSnapshot,
  getSnapshot,
  listSnapshots,
  createOpportunity,
  getOpportunity,
  listOpportunities,
  updateOpportunity,
  approveOpportunity,
  archiveOpportunity,
  createBlocker,
  getBlocker,
  listBlockers,
  updateBlocker,
  resolveBlocker,
  ignoreBlocker,
  createNextAction,
  getNextAction,
  listNextActions,
  updateNextAction,
  completeNextAction,
  skipNextAction,
  getMetroReadiness,
  getAllMetroReadiness,
};

export {
  openMetro,
  createComingSoonPage,
  createMetroFromTemplate,
  getMetroChecklist,
  updateChecklistItem,
  updateMetroStatus,
  getPlatformPrice,
  getEffectivePrice,
  getEffectivePriceByKey,
  auditStripeSync,
  getPricingSummary,
  handleCoraRequest,
  suggestSources,
  generateFromApprovedSources,
  selectContentSources,
  resolveHat,
  createPlan,
  approvePlan,
  rejectPlan,
  getPlan,
  listPlans,
  buildFromPlan,
  listBuildLogs,
  getBuildLog,
  revertBuild,
  createOutreachDraft,
  approveOutreach,
  archiveOutreach,
  updateOutreach,
  getOutreach,
  listOutreach,
  createVoiceScriptDraft,
  createUiProposal,
  approveProposal,
  revertProposal,
  updateProposal,
  getProposal,
  listProposals,
  isRecommendationRequest,
  formatRecommendationResponse,
  createVoiceProfile,
  getVoiceProfile,
  listVoiceProfiles,
  updateVoiceProfile,
  activateVoiceProfile,
  archiveVoiceProfile,
  seedDefaultVoiceProfiles,
  createCallCampaign,
  getCallCampaign,
  listCallCampaigns,
  updateCallCampaign,
  transitionCampaignStatus,
  archiveCallCampaign,
  createCallTask,
  listCallTasks,
  updateCallTask,
  createAnswerFlow,
  getAnswerFlow,
  listAnswerFlows,
  updateAnswerFlow,
  approveAnswerFlow,
  rejectAnswerFlow,
  archiveAnswerFlow,
  createOutboundFlow,
  getOutboundFlow,
  listOutboundFlows,
  updateOutboundFlow,
  approveOutboundFlow,
  rejectOutboundFlow,
  archiveOutboundFlow,
  getVoiceProvider,
  isVoiceProviderConfigured,
  generateSnapshot,
  getSnapshot,
  listSnapshots,
  createOpportunity,
  getOpportunity,
  listOpportunities,
  updateOpportunity,
  approveOpportunity,
  archiveOpportunity,
  createBlocker,
  getBlocker,
  listBlockers,
  updateBlocker,
  resolveBlocker,
  ignoreBlocker,
  createNextAction,
  getNextAction,
  listNextActions,
  updateNextAction,
  completeNextAction,
  skipNextAction,
  getMetroReadiness,
  getAllMetroReadiness,
};
