import { useState, useEffect } from "react";
import { useQuery, useMutation } from "@tanstack/react-query";
import { queryClient, apiRequest } from "@/lib/queryClient";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { Badge } from "@/components/ui/badge";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogFooter } from "@/components/ui/dialog";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Label } from "@/components/ui/label";
import { Switch } from "@/components/ui/switch";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { useToast } from "@/hooks/use-toast";
import { Plus, Pencil, Copy, Trash2, Sparkles, Eye, Newspaper, MapPin, X } from "lucide-react";
import type { PulseIssue, City, PulseBusinessEntry } from "@shared/schema";

interface PulseIssuesPanelProps {
  selectedCityId?: number | string;
}

export default function PulseIssuesPanel({ selectedCityId }: PulseIssuesPanelProps) {
  const { toast } = useToast();
  const [editDialogOpen, setEditDialogOpen] = useState(false);
  const [generateDialogOpen, setGenerateDialogOpen] = useState(false);
  const [editingIssue, setEditingIssue] = useState<PulseIssue | null>(null);
  const [activeTab, setActiveTab] = useState("issues");

  const { data: cities } = useQuery<City[]>({ queryKey: ["/api/admin/cities"] });
  const selectedCity = cities?.find((c) => String(c.id) === String(selectedCityId));

  const { data: issues = [], isLoading } = useQuery<PulseIssue[]>({
    queryKey: ["/api/admin/pulse-issues", selectedCityId],
    queryFn: () => apiRequest("GET", `/api/admin/pulse-issues${selectedCityId ? `?cityId=${selectedCityId}` : ""}`).then(r => r.json()),
  });

  const { data: pickupLocations = [] } = useQuery({
    queryKey: ["/api/admin/pulse-pickup-locations", selectedCityId],
    queryFn: () => apiRequest("GET", `/api/admin/pulse-pickup-locations${selectedCityId ? `?cityId=${selectedCityId}` : ""}`).then(r => r.json()),
  });

  const createMutation = useMutation({
    mutationFn: (data: Record<string, unknown>) => apiRequest("POST", "/api/admin/pulse-issues", data).then(r => r.json()),
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ["/api/admin/pulse-issues"] });
      setEditDialogOpen(false);
      setEditingIssue(null);
      toast({ title: "Issue created" });
    },
    onError: (err: Error) => toast({ title: "Error", description: err.message, variant: "destructive" }),
  });

  const updateMutation = useMutation({
    mutationFn: ({ id, data }: { id: string; data: Record<string, unknown> }) => apiRequest("PATCH", `/api/admin/pulse-issues/${id}`, data).then(r => r.json()),
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ["/api/admin/pulse-issues"] });
      setEditDialogOpen(false);
      setEditingIssue(null);
      toast({ title: "Issue updated" });
    },
    onError: (err: Error) => toast({ title: "Error", description: err.message, variant: "destructive" }),
  });

  const duplicateMutation = useMutation({
    mutationFn: (id: string) => apiRequest("POST", `/api/admin/pulse-issues/${id}/duplicate`).then(r => r.json()),
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ["/api/admin/pulse-issues"] });
      toast({ title: "Issue duplicated as draft" });
    },
  });

  const deleteMutation = useMutation({
    mutationFn: (id: string) => apiRequest("DELETE", `/api/admin/pulse-issues/${id}`),
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ["/api/admin/pulse-issues"] });
      toast({ title: "Issue deleted" });
    },
  });

  const generateMutation = useMutation({
    mutationFn: (data: Record<string, unknown>) => apiRequest("POST", "/api/admin/pulse-issues/generate", data).then(r => r.json()),
    onSuccess: (data: PulseIssue) => {
      queryClient.invalidateQueries({ queryKey: ["/api/admin/pulse-issues"] });
      setGenerateDialogOpen(false);
      toast({ title: "Issue draft generated by Charlotte" });
      setEditingIssue(data);
      setEditDialogOpen(true);
    },
    onError: (err: Error) => toast({ title: "Generation failed", description: err.message, variant: "destructive" }),
  });

  const createPickupMutation = useMutation({
    mutationFn: (data: Record<string, unknown>) => apiRequest("POST", "/api/admin/pulse-pickup-locations", data).then(r => r.json()),
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ["/api/admin/pulse-pickup-locations"] });
      toast({ title: "Pickup location added" });
    },
  });

  const deletePickupMutation = useMutation({
    mutationFn: (id: string) => apiRequest("DELETE", `/api/admin/pulse-pickup-locations/${id}`),
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ["/api/admin/pulse-pickup-locations"] });
      toast({ title: "Pickup location removed" });
    },
  });

  const statusBadge = (status: string) => {
    const colors: Record<string, string> = {
      draft: "bg-gray-100 text-gray-800",
      review: "bg-amber-100 text-amber-800",
      published: "bg-green-100 text-green-800",
      archived: "bg-red-100 text-red-800",
    };
    return <Badge className={colors[status] || ""}>{status}</Badge>;
  };

  return (
    <div className="space-y-6">
      <div className="flex items-center justify-between">
        <div>
          <h2 className="text-2xl font-bold flex items-center gap-2" data-testid="text-pulse-issues-title">
            <Newspaper className="h-6 w-6" /> Hub Pulse Issues
          </h2>
          <p className="text-sm text-muted-foreground mt-1">Manage print-to-digital monthly publications for micro hubs</p>
        </div>
        <div className="flex gap-2">
          <Button variant="outline" onClick={() => setGenerateDialogOpen(true)} data-testid="button-generate-issue">
            <Sparkles className="h-4 w-4 mr-1" /> Charlotte Generate
          </Button>
          <Button onClick={() => { setEditingIssue(null); setEditDialogOpen(true); }} data-testid="button-create-issue">
            <Plus className="h-4 w-4 mr-1" /> New Issue
          </Button>
        </div>
      </div>

      <Tabs value={activeTab} onValueChange={setActiveTab}>
        <TabsList>
          <TabsTrigger value="issues" data-testid="tab-issues">Issues</TabsTrigger>
          <TabsTrigger value="pickups" data-testid="tab-pickups">Pickup Locations</TabsTrigger>
        </TabsList>

        <TabsContent value="issues" className="space-y-3 mt-4">
          {isLoading ? (
            <p className="text-sm text-muted-foreground">Loading...</p>
          ) : issues.length === 0 ? (
            <Card><CardContent className="py-8 text-center text-muted-foreground">No pulse issues yet. Create one or use Charlotte to generate a draft.</CardContent></Card>
          ) : (
            issues.map((issue) => (
              <Card key={issue.id} data-testid={`card-issue-${issue.id}`}>
                <CardContent className="py-4">
                  <div className="flex items-center justify-between">
                    <div className="space-y-1">
                      <div className="flex items-center gap-2">
                        <span className="text-xs font-mono text-muted-foreground">#{issue.issueNumber}</span>
                        <h3 className="font-semibold" data-testid={`text-issue-title-${issue.id}`}>{issue.title}</h3>
                        {statusBadge(issue.status)}
                      </div>
                      <p className="text-sm text-muted-foreground">
                        {issue.hubSlug} &middot; /{selectedCity?.slug || "city"}/hub/{issue.hubSlug}/pulse/{issue.slug}
                      </p>
                    </div>
                    <div className="flex items-center gap-1">
                      {issue.status === "published" && (
                        <Button variant="ghost" size="icon" asChild data-testid={`button-view-issue-${issue.id}`}>
                          <a href={`/${selectedCity?.slug || "charlotte"}/hub/${issue.hubSlug}/pulse/${issue.slug}`} target="_blank">
                            <Eye className="h-4 w-4" />
                          </a>
                        </Button>
                      )}
                      <Button variant="ghost" size="icon" onClick={() => { setEditingIssue(issue); setEditDialogOpen(true); }} data-testid={`button-edit-issue-${issue.id}`}>
                        <Pencil className="h-4 w-4" />
                      </Button>
                      <Button variant="ghost" size="icon" onClick={() => duplicateMutation.mutate(issue.id)} data-testid={`button-duplicate-issue-${issue.id}`}>
                        <Copy className="h-4 w-4" />
                      </Button>
                      <Button variant="ghost" size="icon" onClick={() => { if (confirm("Delete this issue?")) deleteMutation.mutate(issue.id); }} data-testid={`button-delete-issue-${issue.id}`}>
                        <Trash2 className="h-4 w-4 text-destructive" />
                      </Button>
                    </div>
                  </div>
                </CardContent>
              </Card>
            ))
          )}
        </TabsContent>

        <TabsContent value="pickups" className="space-y-3 mt-4">
          <PickupLocationsManager
            locations={pickupLocations}
            cityId={String(selectedCityId || "")}
            onCreate={(data: Record<string, unknown>) => createPickupMutation.mutate(data)}
            onDelete={(id: string) => deletePickupMutation.mutate(id)}
          />
        </TabsContent>
      </Tabs>

      <IssueEditDialog
        open={editDialogOpen}
        onClose={() => { setEditDialogOpen(false); setEditingIssue(null); }}
        issue={editingIssue}
        cityId={String(selectedCityId || "")}
        onSave={(data: Record<string, unknown>) => {
          if (editingIssue) {
            updateMutation.mutate({ id: editingIssue.id, data });
          } else {
            createMutation.mutate(data);
          }
        }}
        isPending={createMutation.isPending || updateMutation.isPending}
      />

      <GenerateDialog
        open={generateDialogOpen}
        onClose={() => setGenerateDialogOpen(false)}
        cityId={String(selectedCityId || "")}
        onGenerate={(data: Record<string, unknown>) => generateMutation.mutate(data)}
        isPending={generateMutation.isPending}
      />
    </div>
  );
}

function parseExistingEntries(entries: unknown): PulseBusinessEntry[] {
  if (!Array.isArray(entries)) return [];
  return entries.map((e: Record<string, string>): PulseBusinessEntry => {
    if (e.type === "manual") {
      return {
        type: "manual",
        name: e.name || "",
        description: e.description || "",
        imageUrl: e.imageUrl || "",
        ctaText: e.ctaText || "",
        ctaUrl: e.ctaUrl || "",
      };
    }
    return { type: "linked", businessId: e.businessId || "" };
  });
}

function BusinessEntryEditor({ entries, onChange, label }: {
  entries: PulseBusinessEntry[];
  onChange: (entries: PulseBusinessEntry[]) => void;
  label: string;
}) {
  const [linkedIdInput, setLinkedIdInput] = useState("");

  const addLinked = () => {
    const ids = linkedIdInput.split("\n").map(s => s.trim()).filter(Boolean);
    if (ids.length === 0) return;
    const newEntries: PulseBusinessEntry[] = ids.map(id => ({ type: "linked" as const, businessId: id }));
    onChange([...entries, ...newEntries]);
    setLinkedIdInput("");
  };

  const addManual = () => {
    onChange([...entries, { type: "manual" as const, name: "", description: "", imageUrl: "", ctaText: "", ctaUrl: "" }]);
  };

  const removeEntry = (idx: number) => {
    onChange(entries.filter((_, i) => i !== idx));
  };

  const updateManualEntry = (idx: number, field: string, value: string) => {
    const updated = entries.map((e, i) => {
      if (i !== idx || e.type !== "manual") return e;
      return { ...e, [field]: value };
    });
    onChange(updated);
  };

  return (
    <div className="space-y-3">
      <Label>{label}</Label>

      {entries.length > 0 && (
        <div className="space-y-2">
          {entries.map((entry, idx) => (
            <Card key={idx} className="relative">
              <Button
                variant="ghost"
                size="icon"
                className="absolute top-1 right-1 h-6 w-6"
                onClick={() => removeEntry(idx)}
                data-testid={`button-remove-entry-${idx}`}
              >
                <X className="h-3 w-3" />
              </Button>
              <CardContent className="py-2 px-3">
                {entry.type === "linked" ? (
                  <div className="flex items-center gap-2 pr-6">
                    <Badge variant="outline" className="text-xs shrink-0">Linked</Badge>
                    <span className="text-xs font-mono text-muted-foreground truncate">{entry.businessId}</span>
                  </div>
                ) : (
                  <div className="space-y-2 pr-6">
                    <Badge variant="outline" className="text-xs">Manual</Badge>
                    <div className="grid grid-cols-2 gap-2">
                      <Input
                        placeholder="Name"
                        value={entry.name || ""}
                        onChange={e => updateManualEntry(idx, "name", e.target.value)}
                        className="h-8 text-sm"
                        data-testid={`input-manual-name-${idx}`}
                      />
                      <Input
                        placeholder="Image URL"
                        value={entry.imageUrl || ""}
                        onChange={e => updateManualEntry(idx, "imageUrl", e.target.value)}
                        className="h-8 text-sm"
                        data-testid={`input-manual-image-${idx}`}
                      />
                    </div>
                    <Input
                      placeholder="Description"
                      value={entry.description || ""}
                      onChange={e => updateManualEntry(idx, "description", e.target.value)}
                      className="h-8 text-sm"
                      data-testid={`input-manual-desc-${idx}`}
                    />
                    <div className="grid grid-cols-2 gap-2">
                      <Input
                        placeholder="CTA Text"
                        value={entry.ctaText || ""}
                        onChange={e => updateManualEntry(idx, "ctaText", e.target.value)}
                        className="h-8 text-sm"
                        data-testid={`input-manual-cta-text-${idx}`}
                      />
                      <Input
                        placeholder="CTA URL"
                        value={entry.ctaUrl || ""}
                        onChange={e => updateManualEntry(idx, "ctaUrl", e.target.value)}
                        className="h-8 text-sm"
                        data-testid={`input-manual-cta-url-${idx}`}
                      />
                    </div>
                  </div>
                )}
              </CardContent>
            </Card>
          ))}
        </div>
      )}

      <div className="flex gap-2">
        <Button variant="outline" size="sm" onClick={addManual} data-testid="button-add-manual-entry">
          <Plus className="h-3 w-3 mr-1" /> Manual Entry
        </Button>
      </div>

      <div className="space-y-1">
        <Label className="text-xs text-muted-foreground">Link businesses by ID (one per line)</Label>
        <Textarea
          value={linkedIdInput}
          onChange={e => setLinkedIdInput(e.target.value)}
          rows={3}
          placeholder="Paste business UUIDs, one per line"
          className="text-xs font-mono"
          data-testid="input-linked-ids"
        />
        <Button variant="outline" size="sm" onClick={addLinked} disabled={!linkedIdInput.trim()} data-testid="button-add-linked">
          <Plus className="h-3 w-3 mr-1" /> Add Linked
        </Button>
      </div>
    </div>
  );
}

interface IssueFormData {
  title: string;
  slug: string;
  hubSlug: string;
  issueNumber: number;
  intro: string;
  heroImageUrl: string;
  heroCtaText: string;
  heroCtaUrl: string;
  featuredStoryTitle: string;
  featuredStoryImage: string;
  featuredStoryBody: string;
  featuredStoryCtaText: string;
  featuredStoryCtaUrl: string;
  quickHitsText: string;
  featuredBusinesses: PulseBusinessEntry[];
  advertisers: PulseBusinessEntry[];
  giveawayEnabled: boolean;
  giveawayTitle: string;
  giveawayText: string;
  giveawayCtaText: string;
  giveawayCtaUrl: string;
  conversionTitle: string;
  conversionText: string;
  conversionCtaText: string;
  conversionCtaUrl: string;
  status: string;
}

function IssueEditDialog({ open, onClose, issue, cityId, onSave, isPending }: {
  open: boolean;
  onClose: () => void;
  issue: PulseIssue | null;
  cityId: string;
  onSave: (data: Record<string, unknown>) => void;
  isPending: boolean;
}) {
  const [tab, setTab] = useState("basics");
  const [formData, setFormData] = useState<IssueFormData>({
    title: "", slug: "", hubSlug: "", issueNumber: 1, intro: "",
    heroImageUrl: "", heroCtaText: "", heroCtaUrl: "",
    featuredStoryTitle: "", featuredStoryImage: "", featuredStoryBody: "",
    featuredStoryCtaText: "", featuredStoryCtaUrl: "",
    quickHitsText: "", featuredBusinesses: [], advertisers: [],
    giveawayEnabled: false, giveawayTitle: "", giveawayText: "",
    giveawayCtaText: "", giveawayCtaUrl: "",
    conversionTitle: "", conversionText: "", conversionCtaText: "", conversionCtaUrl: "",
    status: "draft",
  });

  useEffect(() => {
    if (!open) return;
    if (issue) {
      setFormData({
        title: issue.title || "",
        slug: issue.slug || "",
        hubSlug: issue.hubSlug || "",
        issueNumber: issue.issueNumber || 1,
        intro: issue.intro || "",
        heroImageUrl: issue.heroImageUrl || "",
        heroCtaText: issue.heroCtaText || "",
        heroCtaUrl: issue.heroCtaUrl || "",
        featuredStoryTitle: issue.featuredStoryTitle || "",
        featuredStoryImage: issue.featuredStoryImage || "",
        featuredStoryBody: issue.featuredStoryBody || "",
        featuredStoryCtaText: issue.featuredStoryCtaText || "",
        featuredStoryCtaUrl: issue.featuredStoryCtaUrl || "",
        quickHitsText: Array.isArray(issue.quickHits) ? (issue.quickHits as string[]).join("\n") : "",
        featuredBusinesses: parseExistingEntries(issue.featuredBusinesses),
        advertisers: parseExistingEntries(issue.advertisers),
        giveawayEnabled: issue.giveawayEnabled || false,
        giveawayTitle: issue.giveawayTitle || "",
        giveawayText: issue.giveawayText || "",
        giveawayCtaText: issue.giveawayCtaText || "",
        giveawayCtaUrl: issue.giveawayCtaUrl || "",
        conversionTitle: issue.conversionTitle || "",
        conversionText: issue.conversionText || "",
        conversionCtaText: issue.conversionCtaText || "",
        conversionCtaUrl: issue.conversionCtaUrl || "",
        status: issue.status || "draft",
      });
    } else {
      setFormData({
        title: "", slug: "", hubSlug: "", issueNumber: 1, intro: "",
        heroImageUrl: "", heroCtaText: "", heroCtaUrl: "",
        featuredStoryTitle: "", featuredStoryImage: "", featuredStoryBody: "",
        featuredStoryCtaText: "", featuredStoryCtaUrl: "",
        quickHitsText: "", featuredBusinesses: [], advertisers: [],
        giveawayEnabled: false, giveawayTitle: "", giveawayText: "",
        giveawayCtaText: "", giveawayCtaUrl: "",
        conversionTitle: "", conversionText: "", conversionCtaText: "", conversionCtaUrl: "",
        status: "draft",
      });
    }
    setTab("basics");
  }, [open, issue]);

  const handleSave = () => {
    const quickHits = formData.quickHitsText?.split("\n").filter((h: string) => h.trim()) || [];
    const data: Record<string, unknown> = {
      title: formData.title,
      slug: formData.slug,
      hubSlug: formData.hubSlug,
      issueNumber: formData.issueNumber,
      intro: formData.intro,
      heroImageUrl: formData.heroImageUrl,
      heroCtaText: formData.heroCtaText,
      heroCtaUrl: formData.heroCtaUrl,
      featuredStoryTitle: formData.featuredStoryTitle,
      featuredStoryImage: formData.featuredStoryImage,
      featuredStoryBody: formData.featuredStoryBody,
      featuredStoryCtaText: formData.featuredStoryCtaText,
      featuredStoryCtaUrl: formData.featuredStoryCtaUrl,
      giveawayEnabled: formData.giveawayEnabled,
      giveawayTitle: formData.giveawayTitle,
      giveawayText: formData.giveawayText,
      giveawayCtaText: formData.giveawayCtaText,
      giveawayCtaUrl: formData.giveawayCtaUrl,
      conversionTitle: formData.conversionTitle,
      conversionText: formData.conversionText,
      conversionCtaText: formData.conversionCtaText,
      conversionCtaUrl: formData.conversionCtaUrl,
      status: formData.status,
      cityId,
      quickHits,
      featuredBusinesses: formData.featuredBusinesses,
      advertisers: formData.advertisers,
    };
    onSave(data);
  };

  const update = (field: keyof IssueFormData, value: string | number | boolean | PulseBusinessEntry[]) =>
    setFormData(prev => ({ ...prev, [field]: value }));

  return (
    <Dialog open={open} onOpenChange={(v) => { if (!v) onClose(); }}>
      <DialogContent className="max-w-3xl max-h-[85vh] overflow-y-auto">
        <DialogHeader>
          <DialogTitle>{issue ? "Edit Pulse Issue" : "New Pulse Issue"}</DialogTitle>
        </DialogHeader>

        <Tabs value={tab} onValueChange={setTab}>
          <TabsList className="grid grid-cols-7 w-full">
            <TabsTrigger value="basics">Basics</TabsTrigger>
            <TabsTrigger value="story">Story</TabsTrigger>
            <TabsTrigger value="hits">Quick Hits</TabsTrigger>
            <TabsTrigger value="businesses">Businesses</TabsTrigger>
            <TabsTrigger value="advertisers">Advertisers</TabsTrigger>
            <TabsTrigger value="giveaway">Giveaway</TabsTrigger>
            <TabsTrigger value="cta">CTA</TabsTrigger>
          </TabsList>

          <TabsContent value="basics" className="space-y-3 mt-3">
            <div className="grid grid-cols-2 gap-3">
              <div>
                <Label>Hub Slug</Label>
                <Input value={formData.hubSlug || ""} onChange={e => update("hubSlug", e.target.value)} placeholder="pineville" data-testid="input-hub-slug" />
              </div>
              <div>
                <Label>Issue Number</Label>
                <Input type="number" value={formData.issueNumber || 1} onChange={e => update("issueNumber", parseInt(e.target.value))} data-testid="input-issue-number" />
              </div>
            </div>
            <div>
              <Label>Title</Label>
              <Input value={formData.title || ""} onChange={e => update("title", e.target.value)} placeholder="Issue title" data-testid="input-title" />
            </div>
            <div>
              <Label>URL Slug</Label>
              <Input value={formData.slug || ""} onChange={e => update("slug", e.target.value)} placeholder="auto-generated if blank" data-testid="input-slug" />
            </div>
            <div>
              <Label>Intro</Label>
              <Textarea value={formData.intro || ""} onChange={e => update("intro", e.target.value)} placeholder="Welcome text" data-testid="input-intro" rows={3} />
            </div>
            <div>
              <Label>Hero Image URL</Label>
              <Input value={formData.heroImageUrl || ""} onChange={e => update("heroImageUrl", e.target.value)} data-testid="input-hero-image" />
            </div>
            <div className="grid grid-cols-2 gap-3">
              <div>
                <Label>Hero CTA Text</Label>
                <Input value={formData.heroCtaText || ""} onChange={e => update("heroCtaText", e.target.value)} data-testid="input-hero-cta-text" />
              </div>
              <div>
                <Label>Hero CTA URL</Label>
                <Input value={formData.heroCtaUrl || ""} onChange={e => update("heroCtaUrl", e.target.value)} data-testid="input-hero-cta-url" />
              </div>
            </div>
            <div>
              <Label>Status</Label>
              <Select value={formData.status || "draft"} onValueChange={v => update("status", v)}>
                <SelectTrigger data-testid="select-status"><SelectValue /></SelectTrigger>
                <SelectContent>
                  <SelectItem value="draft">Draft</SelectItem>
                  <SelectItem value="review">Review</SelectItem>
                  <SelectItem value="published">Published</SelectItem>
                  <SelectItem value="archived">Archived</SelectItem>
                </SelectContent>
              </Select>
            </div>
          </TabsContent>

          <TabsContent value="story" className="space-y-3 mt-3">
            <div>
              <Label>Featured Story Title</Label>
              <Input value={formData.featuredStoryTitle || ""} onChange={e => update("featuredStoryTitle", e.target.value)} data-testid="input-story-title" />
            </div>
            <div>
              <Label>Featured Story Image URL</Label>
              <Input value={formData.featuredStoryImage || ""} onChange={e => update("featuredStoryImage", e.target.value)} data-testid="input-story-image" />
            </div>
            <div>
              <Label>Featured Story Body</Label>
              <Textarea value={formData.featuredStoryBody || ""} onChange={e => update("featuredStoryBody", e.target.value)} rows={10} data-testid="input-story-body" />
            </div>
            <div className="grid grid-cols-2 gap-3">
              <div>
                <Label>Story CTA Text</Label>
                <Input value={formData.featuredStoryCtaText || ""} onChange={e => update("featuredStoryCtaText", e.target.value)} data-testid="input-story-cta-text" />
              </div>
              <div>
                <Label>Story CTA URL</Label>
                <Input value={formData.featuredStoryCtaUrl || ""} onChange={e => update("featuredStoryCtaUrl", e.target.value)} data-testid="input-story-cta-url" />
              </div>
            </div>
          </TabsContent>

          <TabsContent value="hits" className="space-y-3 mt-3">
            <div>
              <Label>Quick Hits (one per line)</Label>
              <Textarea
                value={formData.quickHitsText || ""}
                onChange={e => update("quickHitsText", e.target.value)}
                rows={8}
                placeholder="Fun fact #1&#10;Fun fact #2&#10;Fun fact #3"
                data-testid="input-quick-hits"
              />
              <p className="text-xs text-muted-foreground mt-1">Enter each quick hit / trivia item on its own line</p>
            </div>
          </TabsContent>

          <TabsContent value="businesses" className="space-y-3 mt-3">
            <BusinessEntryEditor
              entries={formData.featuredBusinesses}
              onChange={(entries) => update("featuredBusinesses", entries)}
              label="Featured Businesses"
            />
          </TabsContent>

          <TabsContent value="advertisers" className="space-y-3 mt-3">
            <BusinessEntryEditor
              entries={formData.advertisers}
              onChange={(entries) => update("advertisers", entries)}
              label="Advertisers / Sponsors"
            />
          </TabsContent>

          <TabsContent value="giveaway" className="space-y-3 mt-3">
            <div className="flex items-center gap-2">
              <Switch checked={formData.giveawayEnabled || false} onCheckedChange={v => update("giveawayEnabled", v)} data-testid="switch-giveaway" />
              <Label>Enable Giveaway</Label>
            </div>
            {formData.giveawayEnabled && (
              <>
                <div>
                  <Label>Giveaway Title</Label>
                  <Input value={formData.giveawayTitle || ""} onChange={e => update("giveawayTitle", e.target.value)} data-testid="input-giveaway-title" />
                </div>
                <div>
                  <Label>Giveaway Text</Label>
                  <Textarea value={formData.giveawayText || ""} onChange={e => update("giveawayText", e.target.value)} rows={3} data-testid="input-giveaway-text" />
                </div>
                <div className="grid grid-cols-2 gap-3">
                  <div>
                    <Label>CTA Text</Label>
                    <Input value={formData.giveawayCtaText || ""} onChange={e => update("giveawayCtaText", e.target.value)} data-testid="input-giveaway-cta-text" />
                  </div>
                  <div>
                    <Label>CTA URL</Label>
                    <Input value={formData.giveawayCtaUrl || ""} onChange={e => update("giveawayCtaUrl", e.target.value)} data-testid="input-giveaway-cta-url" />
                  </div>
                </div>
              </>
            )}
          </TabsContent>

          <TabsContent value="cta" className="space-y-3 mt-3">
            <div>
              <Label>Conversion Headline</Label>
              <Input value={formData.conversionTitle || ""} onChange={e => update("conversionTitle", e.target.value)} data-testid="input-conversion-title" />
            </div>
            <div>
              <Label>Conversion Text</Label>
              <Textarea value={formData.conversionText || ""} onChange={e => update("conversionText", e.target.value)} rows={3} data-testid="input-conversion-text" />
            </div>
            <div className="grid grid-cols-2 gap-3">
              <div>
                <Label>CTA Button Text</Label>
                <Input value={formData.conversionCtaText || ""} onChange={e => update("conversionCtaText", e.target.value)} data-testid="input-conversion-cta-text" />
              </div>
              <div>
                <Label>CTA URL</Label>
                <Input value={formData.conversionCtaUrl || ""} onChange={e => update("conversionCtaUrl", e.target.value)} data-testid="input-conversion-cta-url" />
              </div>
            </div>
          </TabsContent>
        </Tabs>

        <DialogFooter>
          <Button variant="outline" onClick={onClose}>Cancel</Button>
          <Button onClick={handleSave} disabled={isPending} data-testid="button-save-issue">
            {isPending ? "Saving..." : issue ? "Update Issue" : "Create Issue"}
          </Button>
        </DialogFooter>
      </DialogContent>
    </Dialog>
  );
}

function GenerateDialog({ open, onClose, cityId, onGenerate, isPending }: {
  open: boolean;
  onClose: () => void;
  cityId: string;
  onGenerate: (data: Record<string, unknown>) => void;
  isPending: boolean;
}) {
  const [districtName, setDistrictName] = useState("");
  const [hubSlug, setHubSlug] = useState("");
  const [issueNumber, setIssueNumber] = useState(1);
  const [theme, setTheme] = useState("");
  const [storyPrompt, setStoryPrompt] = useState("");
  const [quickHitsText, setQuickHitsText] = useState("");
  const [giveawayInfo, setGiveawayInfo] = useState("");
  const [featuredBizIds, setFeaturedBizIds] = useState("");
  const [advertiserIds, setAdvertiserIds] = useState("");

  return (
    <Dialog open={open} onOpenChange={v => { if (!v) onClose(); }}>
      <DialogContent className="max-w-lg max-h-[85vh] overflow-y-auto">
        <DialogHeader>
          <DialogTitle className="flex items-center gap-2">
            <Sparkles className="h-5 w-5 text-purple-600" /> Charlotte Issue Generator
          </DialogTitle>
        </DialogHeader>

        <div className="space-y-3">
          <div className="grid grid-cols-2 gap-3">
            <div>
              <Label>District / Hub Name</Label>
              <Input value={districtName} onChange={e => setDistrictName(e.target.value)} placeholder="Pineville" data-testid="input-gen-district" />
            </div>
            <div>
              <Label>Hub Slug</Label>
              <Input value={hubSlug} onChange={e => setHubSlug(e.target.value)} placeholder="pineville" data-testid="input-gen-hub-slug" />
            </div>
          </div>
          <div className="grid grid-cols-2 gap-3">
            <div>
              <Label>Issue Number</Label>
              <Input type="number" value={issueNumber} onChange={e => setIssueNumber(parseInt(e.target.value))} data-testid="input-gen-issue-number" />
            </div>
            <div>
              <Label>Theme (optional)</Label>
              <Input value={theme} onChange={e => setTheme(e.target.value)} placeholder="Spring Events" data-testid="input-gen-theme" />
            </div>
          </div>
          <div>
            <Label>Story Prompt / Source Notes</Label>
            <Textarea value={storyPrompt} onChange={e => setStoryPrompt(e.target.value)} rows={4} placeholder="Notes or source material for the featured story..." data-testid="input-gen-story" />
          </div>
          <div>
            <Label>Quick Hits (one per line, optional)</Label>
            <Textarea value={quickHitsText} onChange={e => setQuickHitsText(e.target.value)} rows={3} placeholder="Fun facts, trivia..." data-testid="input-gen-quick-hits" />
          </div>
          <div>
            <Label>Featured Business IDs (one per line, optional)</Label>
            <Textarea value={featuredBizIds} onChange={e => setFeaturedBizIds(e.target.value)} rows={3} placeholder="Paste business IDs..." data-testid="input-gen-featured-biz" />
          </div>
          <div>
            <Label>Advertiser Business IDs (one per line, optional)</Label>
            <Textarea value={advertiserIds} onChange={e => setAdvertiserIds(e.target.value)} rows={3} placeholder="Paste advertiser IDs..." data-testid="input-gen-advertisers" />
          </div>
          <div>
            <Label>Giveaway Info (optional)</Label>
            <Input value={giveawayInfo} onChange={e => setGiveawayInfo(e.target.value)} placeholder="Gift card from local business..." data-testid="input-gen-giveaway" />
          </div>
        </div>

        <DialogFooter>
          <Button variant="outline" onClick={onClose}>Cancel</Button>
          <Button
            onClick={() => onGenerate({
              districtName,
              hubSlug,
              cityId,
              issueNumber,
              theme,
              storyPrompt,
              quickHits: quickHitsText.split("\n").filter(h => h.trim()),
              featuredBusinessIds: featuredBizIds.split("\n").filter(id => id.trim()).map(id => id.trim()),
              advertiserIds: advertiserIds.split("\n").filter(id => id.trim()).map(id => id.trim()),
              giveawayInfo: giveawayInfo || undefined,
            })}
            disabled={isPending || !districtName || !hubSlug}
            data-testid="button-generate-submit"
          >
            {isPending ? (
              <><Sparkles className="h-4 w-4 mr-1 animate-spin" /> Generating...</>
            ) : (
              <><Sparkles className="h-4 w-4 mr-1" /> Generate Draft</>
            )}
          </Button>
        </DialogFooter>
      </DialogContent>
    </Dialog>
  );
}

interface PickupLocationItem {
  id: string;
  name: string;
  address: string;
  hubSlug: string;
  latitude?: string | null;
  longitude?: string | null;
}

function PickupLocationsManager({ locations, cityId, onCreate, onDelete }: {
  locations: PickupLocationItem[];
  cityId: string;
  onCreate: (data: Record<string, unknown>) => void;
  onDelete: (id: string) => void;
}) {
  const [name, setName] = useState("");
  const [address, setAddress] = useState("");
  const [hubSlug, setHubSlug] = useState("");
  const [lat, setLat] = useState("");
  const [lng, setLng] = useState("");

  return (
    <div className="space-y-4">
      <Card>
        <CardHeader>
          <CardTitle className="text-sm flex items-center gap-2"><MapPin className="h-4 w-4" /> Add Pickup Location</CardTitle>
        </CardHeader>
        <CardContent className="space-y-3">
          <div className="grid grid-cols-2 gap-3">
            <div>
              <Label>Hub Slug</Label>
              <Input value={hubSlug} onChange={e => setHubSlug(e.target.value)} placeholder="pineville" data-testid="input-pickup-hub" />
            </div>
            <div>
              <Label>Location Name</Label>
              <Input value={name} onChange={e => setName(e.target.value)} placeholder="Town Center Library" data-testid="input-pickup-name" />
            </div>
          </div>
          <div>
            <Label>Address</Label>
            <Input value={address} onChange={e => setAddress(e.target.value)} placeholder="123 Main St" data-testid="input-pickup-address" />
          </div>
          <div className="grid grid-cols-2 gap-3">
            <div>
              <Label>Latitude (optional)</Label>
              <Input value={lat} onChange={e => setLat(e.target.value)} placeholder="35.08" data-testid="input-pickup-lat" />
            </div>
            <div>
              <Label>Longitude (optional)</Label>
              <Input value={lng} onChange={e => setLng(e.target.value)} placeholder="-80.89" data-testid="input-pickup-lng" />
            </div>
          </div>
          <Button
            onClick={() => {
              if (!name || !address || !hubSlug) return;
              onCreate({ cityId, hubSlug, name, address, latitude: lat || null, longitude: lng || null });
              setName(""); setAddress(""); setLat(""); setLng("");
            }}
            disabled={!name || !address || !hubSlug}
            data-testid="button-add-pickup"
          >
            <Plus className="h-4 w-4 mr-1" /> Add Location
          </Button>
        </CardContent>
      </Card>

      {locations.length === 0 ? (
        <p className="text-sm text-muted-foreground text-center py-4">No pickup locations configured</p>
      ) : (
        locations.map((loc) => (
          <Card key={loc.id} data-testid={`card-pickup-${loc.id}`}>
            <CardContent className="py-3 flex items-center justify-between">
              <div>
                <p className="font-medium text-sm">{loc.name}</p>
                <p className="text-xs text-muted-foreground">{loc.address} &middot; {loc.hubSlug}</p>
              </div>
              <Button variant="ghost" size="icon" onClick={() => { if (confirm("Remove?")) onDelete(loc.id); }} data-testid={`button-delete-pickup-${loc.id}`}>
                <Trash2 className="h-4 w-4 text-destructive" />
              </Button>
            </CardContent>
          </Card>
        ))
      )}
    </div>
  );
}
